#!/usr/bin/env node
/**
 * Injects environment variables from Vercel / environment into client-side env.js.
 */

import fs from "node:fs";
import path from "node:path";

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseAnonKey =
  process.env.SUPABASE_ANON_KEY ||
  process.env.SUPABASE_KEY ||
  process.env.SUPABASE_TOKEN ||
  "";

const envContent = `// Auto-generated by tools/generate_env.mjs
window.ENV = {
  SUPABASE_URL: ${JSON.stringify(supabaseUrl)},
  SUPABASE_ANON_KEY: ${JSON.stringify(supabaseAnonKey)}
};
`;

import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB_DIR = path.resolve(__dirname, "..");
const outputPath = path.join(WEB_DIR, "env.js");
fs.writeFileSync(outputPath, envContent, "utf-8");

// Also keep a copy at repo root if running at root level
try {
  fs.writeFileSync(path.resolve("env.js"), envContent, "utf-8");
} catch {}

console.log(`[generate_env] Generated ${outputPath}`);
if (supabaseUrl && supabaseAnonKey) {
  console.log(`[generate_env] Injected Supabase URL: ${supabaseUrl}`);
} else {
  console.log("[generate_env] No Supabase credentials provided; running in offline/local fallback mode.");
}
